minimumReleaseAgeExclude:
  - '@conventional-changelog/git-client@3.0.2'
  - '@conventional-changelog/template@1.2.1'
  - conventional-changelog-conventionalcommits@10.2.1
  - conventional-changelog-preset-loader@6.0.1
  - conventional-changelog-writer@9.1.1
  - conventional-changelog@8.0.1
  - conventional-commits-filter@6.0.1
  - conventional-commits-parser@7.0.1
  - conventional-recommended-bump@12.0.1
